# Compose file file format
# Pay attention to https://bom.so/kVr7Qn
version: "3.8"

services:
  fastapi_ocr:
    # The name will be displayed
    # in docker ps
    container_name: fastapi_ocr
    # Build the image from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    # Expose port 30000
    # ports:
    #   - '30000:30000'
    # network_mode: "host"
    # And set the image name
    image: vuvanthanhtb/fastapi_ocr:0.0.1

  fastapi_ocr_2:
    # The name will be displayed
    # in docker ps
    container_name: fastapi_ocr_2
    # Build the image from Dockerfile
    # build:
    #   context: .
    #   dockerfile: Dockerfile_preloaded
    # Expose port 30000
    ports:
      - "30001:30000"
    # And set the image name
    image: vuvanthanhtb/fastapi_ocr:0.0.2
